/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/newCostume.gltf
*/

// import { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
// import { useLoader } from '@react-three/fiber'
// import { TextureLoader } from 'three/src/loaders/TextureLoader'

export function NewCostume(props) {
    const { nodes, materials } = useGLTF('/models/newCostume.gltf')

    const leatherTextureProps = useTexture({
        map: "/textures/Poly - formal coat/color_map.jpg",
        normalMap: "/textures/Poly - formal coat/normal_map_opengl.jpg",
        roughnessMap: "/textures/Poly - formal coat/roughness_map.jpg",
        aoMap: "/textures/Poly - formal coat/ao_map.jpg",
    });

    return (
        // eslint-disable-next-line react/no-unknown-property, react/prop-types
        <group {...props} dispose={null} position={[props.control.x, props.control.y, props.control.z]} scale={props.camCont.scale}>

            <group position={[0, 1.195, 0]} rotation={[1.541, 0, 0]}>
                <mesh geometry={nodes.Pants_Suit_FlatLay.geometry} material={materials.Suit_WineVelvetSolid} position={[0.036, -0.162, 0.617]} rotation={[-Math.PI, 0, 0]} scale={0.025} />
            </group>



            <mesh geometry={nodes.Pants_Button.geometry} material={materials.Button} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
                <meshStandardMaterial {...leatherTextureProps} />
            </mesh>
            <mesh geometry={nodes.Pants_Suit_Button_Holes.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
                <meshStandardMaterial {...leatherTextureProps} />
            </mesh>
            <mesh geometry={nodes.Pants_Suit_Main.geometry} material={materials.Suit_OlivieSolidBrushedTwill} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
                <meshStandardMaterial {...leatherTextureProps} />
            </mesh>
            <mesh geometry={nodes.Pants_Suit_PocketWelts.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
                <meshStandardMaterial {...leatherTextureProps} />
            </mesh>

            <mesh geometry={nodes.PantsSlim_Button.geometry} material={materials.Button} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
                <meshStandardMaterial {...leatherTextureProps} />
            </mesh>
            <mesh geometry={nodes.PantsSlim_Suit.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
                <meshStandardMaterial {...leatherTextureProps} />
            </mesh>
            <mesh geometry={nodes.PantsSlim_Suit_Button_Holes.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
                <meshStandardMaterial {...leatherTextureProps} />
            </mesh>
            <mesh geometry={nodes.PantsSlim_Suit_PocketWelts.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
                <meshStandardMaterial {...leatherTextureProps} />
            </mesh>

        </group >
    )
}

useGLTF.preload('/models/newCostume.gltf')
