import { createSlice } from "@redux js/toolkit"; // import the createSlice function from the @redux js/toolkit package

const initialState = { // define the initial state of the slice
    isOpen: true,
};

const sidebarSlice = createSlice({ // create the sidebar slice
    name: 'sidebar', // the name of the slice. This will be used as the prefix for the action types generated by the createSlice function.
    initialState, // the initial state of the slice
    reducers: { // the reducers of the slice
        toggleSidebar: (state) => { // this reducer will be used to toggle the sidebar. It will set the isOpen property of the state to the opposite of its current value.
            state.isOpen = !state.isOpen; 
        },
        setSidebarOpenState: (state, action) => { // this reducer will be used to set the isOpen property of the state to the value passed to it.
            state.isOpen = action.payload;
        },
    }
});


export const selectSidebarIsOpen = (state) => state.sidebar.isOpen; // export a selector to get the isOpen property of the state
export const { toggleSidebar, setSidebarOpenState } = sidebarSlice.actions; // export the actions generated by the createSlice function
export default sidebarSlice.reducer;
