/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/newCostume.gltf
*/

// import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NewCostume(props) {
  const { nodes, materials } = useGLTF('../../models/newCostume.gltf')



  return (
    // eslint-disable-next-line react/no-unknown-property
    <group {...props} dispose={null} position={[props.control.x, props.control.y, props.control.z]} scale={props.camCont.scale}>
      {/* <group position={[0.034, -0.389, 0.082]}>
        <mesh geometry={nodes.Jacket_Button002.geometry} material={materials['Button.003']} position={[-1.101, 0.124, 0.012]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
        <mesh geometry={nodes.Jacket_Button003.geometry} material={materials['Button.003']} position={[-1.1, 0.041, 0.032]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      </group>
      <group position={[0, 1.195, 0]} rotation={[1.541, 0, 0]}>
        <mesh geometry={nodes.Pants_Suit_FlatLay.geometry} material={materials.Suit_WineVelvetSolid} position={[0.036, -0.162, 0.617]} rotation={[-Math.PI, 0, 0]} scale={0.025} />
      </group> */}
      {/* <mesh geometry={nodes.JacketSlim_Button001.geometry} material={materials['Button.001']} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} /> */}
      {/* <mesh geometry={nodes.Jacket_Button004.geometry} material={materials['Button.002']} position={[-1.101, 0.124, 0.012]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} /> */}
      {/* <mesh geometry={nodes.Jacket_Button005.geometry} material={materials['Button.002']} position={[-1.273, 0.883, -0.307]} rotation={[-0.741, 0.965, 1.754]} scale={0.025} /> */}
      <mesh geometry={nodes.Jacket_Button006.geometry} material={materials['Button.002']} position={[0.000, -0.100, 0.006]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Jacket_Button006.geometry} material={materials['Button.002']} position={[0.000, -0.180, 0.006]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      {/* <mesh geometry={nodes.Jacket_Button009.geometry} material={materials['Button.002']} position={[0.124, -0.111, 0.028]} rotation={[-1.579, -0.08, -0.739]} scale={0.025} /> */}
      {/* <mesh geometry={nodes.Shoes.geometry} material={materials.Shoes} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} /> */}
      <mesh geometry={nodes.Tie.geometry} material={materials.Tie} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Jacket_Button.geometry} material={materials.Button} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Jacket_Lining.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Jacket_Lining_Tag.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Jacket_Suit_Button_Holes.geometry} material={materials.Suit_WineVelvetSolid} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Jacket_Suit_ChestPocket.geometry} material={materials.Suit_WineVelvetSolid} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Jacket_Suit_PocketFlaps.geometry} material={materials.Suit_NavyWindowpane} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Jacket_Suit_PocketWelts.geometry} material={materials.Suit_WineVelvetSolid} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Jacket_Suit_Notch_NoVents.geometry} material={materials.Suit_NaturalStoneStripe} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Jacket_Suit_Notch_Vents.geometry} material={materials.Suit_DarkBrownPlaid} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Jacket_Suit__Peak_Vents.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Jacket_Suit_Peak_NoVents.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      {/* <mesh geometry={nodes.Pants_Button.geometry} material={materials.Button} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Pants_Suit_Button_Holes.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Pants_Suit_Main.geometry} material={materials.Suit_OlivieSolidBrushedTwill} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Pants_Suit_PocketWelts.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} /> */}
      <mesh geometry={nodes.Shirt_Button.geometry} material={materials.Button} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Shirt_Button_Holes.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Shirt_Main.geometry} material={materials.ShirtFabric} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Vest_Button.geometry} material={materials.Button} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Vest_Lining.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Vest_Lining_Tag.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Vest_Strap.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Vest_Suit_Button_Holes.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Vest_Suit_Main.geometry} material={materials.Suit_NavyWindowpane} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      {/* <mesh geometry={nodes.Shoes_Slim.geometry} material={materials.Shoes} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} /> */}
      <mesh geometry={nodes.TieSlim.geometry} material={materials.Tie} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.JacketSlim_Button.geometry} material={materials.Button} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.JacketSlim_Lining_Tag.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.JacketSlim_Suit_Button_Holes.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.JacketSlim_Suit_Notch_NoVents.geometry} material={materials.Suit_WineVelvetSolid} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.JacketSlim_Suit_Notch_Vents.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.JacketSlim_Suit_Peak_NoVents.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.JacketSlim_Suit_Peak_Vents.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      {/* <mesh geometry={nodes.PantsSlim_Button.geometry} material={materials.Button} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.PantsSlim_Suit.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.PantsSlim_Suit_Button_Holes.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.PantsSlim_Suit_PocketWelts.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} /> */}
      <mesh geometry={nodes.ShirtSlim.geometry} material={materials.ShirtFabric} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.ShirtSlim_Button.geometry} material={materials.Button} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.ShirtSlim_Button_Holes.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.VestSlim_Button.geometry} material={materials.Button} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.VestSlim_Lining_Tag.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.VestSlim_Strap.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.VestSlim_Suit.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.VestSlim_Suit_Button_Holes.geometry} material={materials.b0b0b0} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      {/* <mesh geometry={nodes.Jacket_Button007.geometry} material={materials['Button.004']} position={[-1.056, -0.368, 0.175]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} /> */}
      {/* <mesh geometry={nodes.Jacket_Button008.geometry} material={materials['Button.005']} position={[-1.056, -0.368, 0.175]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} /> */}
    </group>
  )
}

useGLTF.preload('../../models/newCostume.gltf')
