/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/suit1.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Suit1(props) {
  const { nodes, materials } = useGLTF('../../models/suit1.gltf')
  return (
    <group {...props} dispose={null} rotation={[Math.PI / -2, 0, 1.5]} position={[0.831, -10.882, 15.734]} scale={0.705}>
      <mesh geometry={nodes.suit.geometry} material={materials['Material.001']} position={[-2.116, 4.011, 65.734]} rotation={[Math.PI / 2, 0, 0]} scale={1.016} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.hitman_shirt_for_upload.geometry} material={materials['FABRIC 1_FRONT_4917.001']} />
        <mesh geometry={nodes.hitman_shirt_for_upload_1.geometry} material={materials['FABRIC 3_FRONT_4922']} />
        <mesh geometry={nodes.hitman_shirt_for_upload_2.geometry} material={materials['Material3579.001']} />
        <mesh geometry={nodes.hitman_shirt_for_upload_3.geometry} material={materials['PT_FABRIC_FRONT_4954.001']} />
      </group>
      <mesh geometry={nodes.pant.geometry} material={materials['FABRIC 1_FRONT_4917.002']} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-0.831, -1.882, -24.638]} rotation={[Math.PI / 2, 0, 0]} scale={0.705}>
        <mesh geometry={nodes.marv_suit_singles_bdy_front_1.geometry} material={materials.Body_F_FRONT_181989} />
        <mesh geometry={nodes.marv_suit_singles_bdy_front_1_1.geometry} material={materials.Material182008} />
        <mesh geometry={nodes.marv_suit_singles_bdy_front_1_2.geometry} material={materials.BASIC_FABRIC_FRONT_14903} />
        <mesh geometry={nodes.marv_suit_singles_bdy_front_1_3.geometry} material={materials.Body_F_StandCollar_FRONT_181993} />
      </group>
      <group position={[-2.25, -6.495, -24.891]} rotation={[Math.PI / 2, 0, 0]} scale={0.705}>
        <mesh geometry={nodes.marv_suit_singles_bdy_front_1001.geometry} material={materials['Body_F_FRONT_181989.001']} />
        <mesh geometry={nodes.marv_suit_singles_bdy_front_1001_1.geometry} material={materials['Material182008.001']} />
        <mesh geometry={nodes.marv_suit_singles_bdy_front_1001_2.geometry} material={materials['BASIC_FABRIC_FRONT_14903.001']} />
        <mesh geometry={nodes.marv_suit_singles_bdy_front_1001_3.geometry} material={materials['Body_F_StandCollar_FRONT_181993.001']} />
      </group>
      <group position={[-1.044, -2.081, -25.195]} rotation={[Math.PI / 2, 0, 0]} scale={0.705}>
        <mesh geometry={nodes.marv_suit_singles_bdy_front_1002.geometry} material={materials['Body_F_FRONT_181989.001']} />
        <mesh geometry={nodes.marv_suit_singles_bdy_front_1002_1.geometry} material={materials['Material182008.001']} />
        <mesh geometry={nodes.marv_suit_singles_bdy_front_1002_2.geometry} material={materials['BASIC_FABRIC_FRONT_14903.001']} />
        <mesh geometry={nodes.marv_suit_singles_bdy_front_1002_3.geometry} material={materials['Body_F_StandCollar_FRONT_181993.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('../../models/suit1.gltf')
